"""
Module containing a class Node that represents a node in the search tree
"""


class Node:
    """
    Node class represents a node in the search tree
    """

    def __init__(self, retrons_to_expand: tuple = None, new_retrons: tuple = None) -> None:
        """
        The function initializes the new Node object.

        :param retrons_to_expand: The tuple of retrons to be expanded. The first retron in the tuple is the current
        retron which will be expanded (for which new retrons will be generated by applying the predicted reaction
        rules). When the first retron has been successfully expanded, the second retron becomes the current retron
        to be expanded.
        :param new_retrons: The tuple of new retrons generated by applying the reaction rule. New retrons have already
        been added to the retrons_to_expand (see Tree._expand_node). Here they are stored for information.
        """

        self.retrons_to_expand = retrons_to_expand
        self.new_retrons = new_retrons

        if len(self.retrons_to_expand) == 0:
            self.curr_retron = tuple()
        else:
            self.curr_retron = self.retrons_to_expand[0]
            self.next_retrons = self.retrons_to_expand[1:]

    def __len__(self) -> int:
        """
        The number of retrons in this node to expand.
        """
        return len(self.retrons_to_expand)

    def __repr__(self) -> str:
        """
        String representation of the node. Returns the smiles of retrons_to_expand and new_retrons.
        """
        return f"retrons_to_expand: {self.retrons_to_expand}\nnew_retrons: {self.new_retrons}"

    def is_solved(self) -> bool:
        """
        Is terminal node. There are not retrons for expansion.
        """

        return len(self.retrons_to_expand) == 0
